### ISSUE TITLE
Add support to spawn _meta header and footer patterns if not found

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternengine-node-nunjucks#2]
This engine should spawn its own `_meta/` files if not present.

Follow the commits within https://github.com/pattern-lab/patternengine-node-handlebars/commit/3dd846b68561d5b2a333a8d389c5f061bd034b52

**Comment by dnwhte** [comment]
Will jump on this shortly

**Comment by dnwhte** [comment]
Merged #4
