### ISSUE TITLE
How to use this with patternlab-node v3?

### ISSUE THREAD

**Issue by ghost** [pattern-lab/patternengine-node-nunjucks#5]
I am just starting out with patternlab and am trying to setup a new library, with the intended idea of using nunjucks instead of mustache for templates and components (and all other patterns as well).

Since I have found nothing nowhere (or maybe I am too stupid): could you please enlighten me, how I would tell my patternlab instance (plain node, working so far) how to use this lib instead of the default mustache one?

Thanks a lot!

**Comment by dnwhte** [comment]
Hi @webgefrickel 

Thanks for the interest. I'm currently working on support for v3. You can use it by installing the dev branch (https://github.com/pattern-lab/patternlab-node#dev in your package.json).

1. Install the dev branch
2. Set "patternExtension": "njk" in patternlab-config.json
3. Create patterns with the .njk extension and you're on your way

Let me know if you have any further issues.

**Comment by ghost** [comment]
Thanks a lot, @danwhite85 — this seems to work! I am gonna fiddle around with this for a while now, and report back if I run into any issues.
