### ISSUE TITLE
Not working with Webpack Edition

### ISSUE THREAD

**Issue by ivandoric** [pattern-lab/patternengine-node-nunjucks#7]
I don't know if I should open this here or on the Wepack edition page. I will probably open issue there also. Anyway just to let you know that this is not working with https://github.com/Comcast/patternlab-edition-node-webpack

I tried it some moons ago with Gupl edition and it worked fine, but with Webpack instead of displaying HTML of a pattern I just get `[Object promise]`. And I'm not even using nunjucks on a pattern, my code is just something like `<button>Button</button>`, file just has `.njk`extension. Working with mustache right now but would really like to use nunjucks because I think it's more expressive.

**Comment by ivandoric** [comment]
Works, but only version 0.1.2 not the latest one.

**Comment by dnwhte** [comment]
@ivandoric in 0.1.3 I did some work to make it compatible with Pattern Lab v3. My guess is that it's because the Webpack edition is still running PL v2.
